### ISSUE TITLE
Landscape mode off-center?

### ISSUE THREAD

**Issue by jblk01** [thetorine/Samaritan#2]
Hello, on most devices, when I use the landscape mode, the words are off center as in they go off screen to the right.  I have been able to repeat this on various Android devices at my disposal.

I have found that it works as intended with a Google Nexsus running Android 5

Would you be willing to update the apk and push this out for others as I have confirmation that they are also having issues as well?  I would personally like to load this on Remix OS and use it on a large screen like in the show.

Regards,

jblk01
![screenshot_2016-12-30-15-19-30](https://cloud.githubusercontent.com/assets/24847127/21572871/e2234a46-cea3-11e6-8f8d-4b04b031ac73.png)

**Comment by thetorine** [comment]
Does it not work on Google Nexus 5 running a version greater than lollipop? I'll look into the issue but I only have one android device (Nexus 5) to test on.

Never mind I can try run it on the emulator.

**Comment by thetorine** [comment]
Alright I was able to replicate the problem. I'll try and find out why and fix it.

**Comment by thetorine** [comment]
The screen height was hard-coded as 1920 pixels. :)

**Comment by jblk01** [comment]
Thank you, I am testing it on different devices currently and have responded to your message on reddit.

On a Sony Xperia T running Android 4.1.2 and on an LG G Pad 7 running Android 5.0.2 here are the results:

On the Xperia it displays correctly but the line doesn't realign properly:

![sony xperia t result](https://cloud.githubusercontent.com/assets/24847127/21793818/55ce42e8-d6ba-11e6-812b-7545db77ba83.png)


And then on the LG GPad the words go off the line very slightly but not like before:

![lg gpad result](https://cloud.githubusercontent.com/assets/24847127/21793826/6545142c-d6ba-11e6-9c55-102854fa2c58.png)


Thank you for your work on this application, it is appreciated.  I'd be happy to continue testing as I have multiple Android devices at my disposal.  

Regards,

- Jason
